version: "3.8"
services:
  postgres:
    image: postgres:15.3-alpine
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - postgresql.env
networks:
  default:
    name: local-network
    external: true